version: '3.7'

services:
    arbify:
        # build:
        #     args:
        #         user: arbify
        #         uid: 1000
        #     context: .
        #     dockerfile: docker/arbify/Dockerfile
        image: arbify
        # image: hzgood/arbify
        restart: unless-stopped
        working_dir: /var/www
        command: ["/var/www/docker/arbify/run.sh"]
        # command: sleep 3000
        environment:
            DB_USER: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        volumes:
            - .env:/var/www/.env
            - ./docker/arbify/:/var/www/docker/arbify/

    db:
        image: mariadb:10
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - db-data:/var/lib/mysql

    nginx:
        image: nginx:1.17-alpine
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - .:/var/www
            - ./docker/nginx:/etc/nginx/conf.d

volumes:
    db-data:
