name: PHP

on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer downloads
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Cache project dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}

      - name: Get dependencies
        uses: php-actions/composer@v1

      - name: Setup application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run code sniffer
        run: vendor/bin/phpcs

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Upload tests laravel.log
        uses: actions/upload-artifact@v2
        with:
          name: laravel.log
          path: storage/logs/laravel.log
        if: ${{ failure() }}
