name: PHP

on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get dependencies
        uses: php-actions/composer@v1
      - name: Run tests
        uses: php-actions/phpunit@v1
        with:
          config: phpunit.xml
